apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: confidential-filter
  namespace: confidential-filter
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
spec:
  ingressClassName: nginx
  rules:
    - host: confidential.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
