apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: confidential-filter
resources:
  - namespace.yaml
  - configmap.yaml
  - app-deployment.yaml
  - app-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
