apiVersion: v1
kind: Secret
metadata:
  name: confidential-filter-secrets
  namespace: confidential-filter
type: Opaque
stringData:
  SECRET_KEY: change-me
  MODEL_S3_URI: s3://confedentbaucketden/startmodel
  AWS_ACCESS_KEY_ID: change-me
  AWS_SECRET_ACCESS_KEY: change-me
  AWS_SESSION_TOKEN: ""
  AWS_REGION: ru-1
  AWS_DEFAULT_REGION: ru-1
  S3_ENDPOINT_URL: https://s3.regru.cloud
  REVIEW_DATABASE_URL: ""
  REVIEW_DB_HOST: 79.174.89.192
  REVIEW_DB_PORT: "15694"
  REVIEW_DB_NAME: db1
  REVIEW_DB_USER: user1
  REVIEW_DB_PASSWORD: change-me
  TELEGRAM_BOT_TOKEN: ""
  TELEGRAM_CHAT_ID: ""
  SMTP_HOST: ""
  SMTP_PORT: "587"
  SMTP_USERNAME: ""
  SMTP_PASSWORD: ""
