apiVersion: v1
kind: Service
metadata:
  name: airflow-postgres
  namespace: confidential-filter
spec:
  selector:
    app.kubernetes.io/name: airflow-postgres
    app.kubernetes.io/part-of: confidential-filter
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
